{% set name = "libsemigroups-python-bindings" %}
{% set version = "0.0.1" %}
{% set sha256 = "c150a286a11483ee426b29c83e208a9675b0ed21c601de342453bf58c1b27f02" %}
{% set repo = "https://github.com/james-d-mitchell/libsemigroups-python-bindings" %}
{% set home = "https://james-d-mitchell.github.io/libsemigroups/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # The python bindings are not yet merged in master; fetch them from their git
  # branch instead
  #git_url: {{ repo }}.git
  #git_tag: python-bindings
  url: {{ repo }}/archive/v{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script:
    - export CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include"
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - cython
    - libsemigroups >=0.2.2
    - nose
    # pytest-cython # not yet on conda-forge

  run:
    - python
    - libsemigroups >=0.2.2

test:
  requires:
    - nose
  commands:
    - python -m nose --with-doctest
    
  imports: 
  - semigroups
  source_files:
    - semigroups/*

about:
  home: {{ home }}
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Python bindings for the libsemigroups C++ library for semigroups and monoids'

  description: |
    libsemigroups is a C++ library for semigroups and monoids.
    libsemigroups-python-bindings provides python bindings for it.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
