{% set name = "libsemigroups-python-bindings" %}
{% set version = "0.3.0" %}
{% set sha256 = "9c0691073fbb190a45cbe60d3ec4bf22f99e3ee1cc749b62ec9ed9b0e28366dc" %}
{% set repo = "https://github.com/james-d-mitchell/libsemigroups-python-bindings" %}
{% set home = "https://james-d-mitchell.github.io/libsemigroups-python-bindings/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ repo }}/archive/v{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script:
    - export CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include"
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - cython
    - cysignals
    - libsemigroups >=0.3.0
    - nose

  run:
    - python
    - cysignals
    - libsemigroups >=0.3.0

test:
  requires:
    - nose
  commands:
    - python -m nose --with-doctest
    
  imports: 
  - semigroups
  source_files:
    - semigroups/*

about:
  home: {{ home }}
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Python bindings for the libsemigroups C++ library for semigroups and monoids'

  description: |
    libsemigroups is a C++ library for semigroups and monoids.
    libsemigroups-python-bindings provides python bindings for it.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
