travis:
  secure:
    BINSTAR_TOKEN: G9klt/2Sj1VpCX3ci23Bl8cKywIZKPIbTAHComgMDgkOmvVPufXMi/bkElMscDhD93qQydXsNMLyIgHrBcWr+MJN5JyPNvkJjU1ZgZfdmKfkQvT7t3bkHT/7rrbwbpC4a0YD6dAY9bqOhHZfJ5V/vmQ7syB6dWc5/G54y07LyUbhQhGDcfelEwQ20Ef/ALQqRxQkFbFy1Y1i9dSuQmIMbkJVBnE52m9oWVngY0sFq4lHSa2/BQm9+gFEekdbN58/z70XW09rMl+g/GQavSyJ+6o/RmBsoA7mo8ilRgZmuy4izb5ZKszGtU7v2529LxysXbzpTcGh+BRll3hJEVcR/5gtJ3OD4DVKpB1PHhz77O4UxK7LkT2H1RNpN9vBmnkV2FQYmVmH1oArZcMPE6LQMchon3yXvBIQ7UOGtXZfhQmj0ioe3J40WFeHhSlYHLup/EmJO5qfkF1b80/pz9m7LRRILHMOLX/UgK0bBWCunEl8xLkhFErlf+F5ZA9Tlrxu8AILz1jAW8Fl/xBiinapGrd9kXliWMDxVaGpSpQusUw7LVhzTZUKWzXM5EQlq0Hq9tQcOpqymvsfof9QYJD+HVnjuRGYQirboWw1rBPzGnAle9IeXUGXHVPW7t6EMfVlF/BW9FoIJRzlaFW/0SkidWtTgkP781zu4WJGmbw+SJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
