travis:
  secure:
    BINSTAR_TOKEN: rowtJgPiMTgBoPcgl2YSdC85zgTbJmgD7RTqfqqhTi5OxT47GimLARG0B0VSDmLAZHTlgRF9Q7qZVOmeXyFCA1nHDxea1S53HmipPGntJRXJuP9QeLnMn34G0wl+Z0nDzxkJWxsTs/sUwTVN4c2zffTReqTzxx80fQp0DgBxwgsADGKUx10nl5tq4r97EWKUI7bxD/0rjHF54XbYLs6lcM7L1V7SzuwnlChhjTKcewK9Pc9Z1n/VBSCuYtzIW8AUGJ9sMgqyX48CWeff4/8tkzawTmlZKdxHJ//gg3B8qW5VBHfHgboh2q3tjJGFAzE8IW2sy5xt60RTvrBixMO/Melu+NpqiJf81K0iCMcWtCpgnrhL/mCbkCf5iAz2/XWUMb4WjYTDldV1sD3AGYglGG0SBdWfjr69c8joozmkMHqD3uGrO81koha1y2OsmOllKWfFbWhFpNsbaGJFPMpnFWCvnQmwt4MIG7KT00JklNmskm4oXDilnXpo+GvO3K/z2Dbcq0SKcokDOiYA2oOa5bvAT63aXueOf3Sh3XcYNWHQrLUooOyWSCmFuDNZqioOQahq+FiIbvRzrsoK6/h6ICOOEksrV3Xud2mKBvUdsB0mEyzjyEz8duOnI88wVJi5IQjqURnyWf/5A4LmzJ2+Sxu+mfObPT7sEd0bbiR5rmo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
